---
- name: Demo-1 Playbook
  hosts: leafs
  gather_facts: false
  vars:
    vlan_id: "10"
    vlan_name: Storage_Vlan
  tasks:
    - name: Get vlan information from Switch
      arista.eos.eos_command:
        commands:
          - command: show vlan
            output: json
      register: vlans_output
    
    - name: Print vlan information
      ansible.builtin.debug:
        msg: "{{ vlans_output.stdout_lines[0].vlans.keys() }}"

    - name: Create vlan
      arista.eos.eos_config:
        lines:
          - vlan {{ vlan_id }}
          - name {{ vlan_name }}
        parents: vlan {{ vlan_id }}
      when: vlan_id not in vlans_output.stdout_lines[0].vlans.keys()
