---
# vars file for arista_baseline
dns_domain: testing.com
clock:
  timezone: UTC
ntp_servers:
  - 0.pool.ntp.org
  - time.google.com
static_routes:
  - destination_prefix: 0.0.0.0/0
    gateway: 192.168.0.1
name_servers:
  - 8.8.8.8
  - 1.1.1.1
aaa_root:
  sha512_password: $6$SV63cqAiZoy5nRCo$rXWc/CJSVBN17VtaxaZsvYbY4N4.OihJgZGonBsouKJpHZXIAEbvJAgopkvLQTFiqVYRg4.BX0BJGhD1QX.En.
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$VxMZJSTG1bWpf6sN$vxdnrMRQhmwKRysTjD07HlR.gKEqtkYX7aUMLkyblVYkLbSd6vQol1Ugj2a59Gp7DYkP2eXpKYjpjuMWtWxTA.
management_api_http:
  enable_http: true
  enable_https: true
  enable_unix_socket: true
banners:
  login: |
    #############################################################
    #                                                           #
    #        This switch is part of the Automation lab.         #
    #                                                           #    
    #        All connections are monitored and recorded         #
    #                                                           #
    # disconnect IMMEDIATELY if you are not an authorized user! #                                                           #
    #                                                           #
    #             -- Data Center Team --                        #
    #                                                           #
    #############################################################
    EOF
aaa_authorization:
  exec:
    default: local
  commands:
    all_default: local
aaa_authentication:
  policies:
    local:
      allow_nopassword: true
